alias ls="ls --color=auto"
alias ll="ls -alhtrF --time-style=long-iso --color=auto"
alias grep="grep --color=auto"
alias dir="dir --color=auto"
alias ip="ip -color=auto"
alias diff="diff --color=auto"
alias dmesg="dmesg --color=always"
alias tree="tree -C"
alias rm="rm -i"
alias tk="tmux kill-session -t"
alias tka="tmux kill-session -a"
alias showip="dig +short myip.opendns.com @resolver1.opendns.com"
alias pj="cd /home/core/mydir/projects/"
alias cf="cd /home/core/mydir/confs/"
alias py=python3
alias tts="xclip -o| festival --tts --pipe"
alias dl="cd /tmp/daily"
